Include hierarchy of direct dependencies
Direct dependency classes may be loaded before secondary dex
installation: so their hierarchy is needed in the main dex or they
will be rejected at load and cause NoClassDefFoundError at first use.

Bug: 72039872
Change-Id: Ida42c70f9c8e1c7e16ad779bce7ea038a8124782