Add a test for an invocation of a missing static interface method.
This should throw a NoSuchMethodError but currently will generate
a ClassNotFoundException.

Bug: 69835274
Change-Id: I42536e0de92a7776f8b91d2a2e74fb551e08d539