Desugar super calls in default methods targeting library
This desugares default interface methods calling default methods
in the ilibrary by inserting code to throw a NoSuchMethodError.

Instead of these super calls causing a compile time error they now
cause a runtime error if used.

Bug: 191690646
Change-Id: Id5d88f9e0d6a534796a0ff923248e6146b3ac460